export interface PostgisCatalog {
  tables: Record<string, string[]>
  functions: string[]
  requiredSpatialFunctions: string[]
  maxLimit: number
}

export function createPostgisCatalog(): PostgisCatalog {
  return {
    tables: {
      pois: [
        'id',
        'name',
        'category_main',
        'category_sub',
        'longitude',
        'latitude',
        'city',
        'region_label',
        'location_hint',
        'brand_category',
        'geom',
      ],
      districts: [
        'id',
        'name',
        'eng_name',
        'area_sqm',
        'geom',
      ],
      aois: [
        'id',
        'osm_id',
        'code',
        'fclass',
        'name',
        'population',
        'area_sqm',
        'geom',
      ],
      landuse: [
        'id',
        'land_type',
        'area_sqm',
        'geom',
      ],
      population_grid_100m: [
        'id',
        'source_name',
        'row_index',
        'col_index',
        'pop_value',
        'center_lon',
        'center_lat',
        'geom',
        'center_geom',
        'created_at',
        'updated_at',
      ],
      population_grid: [
        'id',
        'pop_value',
        'center_lon',
        'center_lat',
        'geom',
        'center_geom',
      ],
      cells: [
        'id',
        'cell_id',
        'center_lon',
        'center_lat',
        'dominant_category',
        'aoi_type',
        'scene_tags',
        'geom',
      ],
      road_blocks: [
        'id',
        'name',
        'area_sqm',
        'block_type',
        'geom',
      ],
      roads: [
        'id',
        'name',
        'fclass',
        'code',
        'oneway',
        'maxspeed',
        'layer',
        'bridge',
        'tunnel',
        'geom',
      ],
      streets: [
        'id',
        'name',
        'street_type',
        'geom',
      ],
    },
    functions: [
      'count',
      'sum',
      'avg',
      'min',
      'max',
      'st_dwithin',
      'st_distance',
      'st_setsrid',
      'st_makepoint',
      'st_x',
      'st_y',
      'st_intersects',
      'st_contains',
      'st_buffer',
      'st_astext',
      'st_asgeojson',
      'st_geomfromtext',
      'st_geomfromgeojson',
      'st_squaregrid',
      'st_hexagongrid',
      'st_snaptogrid',
      'st_centroid',
      'st_pointonsurface',
      'st_collect',
      'st_envelope',
      'st_union',
      'st_intersection',
      'st_difference',
      'st_simplify',
      'st_simplifypreservetopology',
      'st_concavehull',
      'st_convexhull',
      'st_clusterdbscan',
      'st_isvalid',
      'st_isempty',
      'st_multi',
      'st_geometrytype',
      'st_makevalid',
      'st_force2d',
      'st_area',
      'row_number',
      'greatest',
      'least',
      'floor',
      'nullif',
      'coalesce',
    ],
    requiredSpatialFunctions: ['st_dwithin', 'st_intersects', 'st_contains'],
    maxLimit: 200,
  }
}
